name       : libstemmer
version    : 2.2.0
release    : 2
source     :
    - https://github.com/snowballstem/snowball/archive/refs/tags/v2.2.0.tar.gz : 425cdb5fba13a01db59a1713780f0662e984204f402d3dae1525bda9e6d30f1a
homepage   : https://snowballstem.org/
license    : BSD-3-Clause
component  : programming.library
summary    : Snowball compiler and stemming algorithms
description: |
    Snowball is a small string processing language for creating stemming algorithms for use in Information Retrieval, plus a collection of stemming algorithms implemented using it.
setup      : |
    %patch -p1 < $pkgfiles/0001-Compile-dynamic-lib.patch
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr/lib64
    install -Dm00755 snowball $installdir/usr/bin/snowball
    install -Dm00755 stemwords $installdir/usr/bin/stemwords
    install -Dm00644 include/libstemmer.h $installdir/usr/include/libstemmer.h
    install -Dm00644 libstemmer.so.%version% $installdir/usr/lib64
    ln -s libstemmer.so.%version% $installdir/usr/lib64/libstemmer.so.2
    ln -s libstemmer.so.%version% $installdir/usr/lib64/libstemmer.so
